name: user-profile
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - configparser
  - pip:
    - "flask[async]>=2.3.3"
    - openai>=1.12.0
    - google-generativeai>=0.3.0
    - tenacity>=8.2.0
    - numpy>=1.24.0
    - python-dotenv>=1.0.0
    - aiohttp>=3.9.0
    - asyncio>=3.4.3 